export const API_BASE_URL =
  process.env.EXPO_PUBLIC_API_URL || "http://localhost:4000";

export const API = {
  auth: {
    login: "/api/auth/login",
    register: "/api/auth/register",
    logout: "/api/auth/logout",
    profile: "/api/auth/profile",
    avatar: "/api/auth/profile/avatar",
    refresh: "/api/auth/refresh",
    changePassword: "/api/auth/change-password",
    forgotPassword: "/api/auth/forgot-password",
    resetPassword: "/api/auth/reset-password",
  },
  users: {
    list: "/api/users",
    byUsername: (u: string) => `/api/users/${u}`,
    follow: (id: string) => `/api/users/${id}/follow`,
    followers: (id: string) => `/api/users/${id}/followers`,
    following: (id: string) => `/api/users/${id}/following`,
    suggested: "/api/users/suggested",
    search: "/api/users/search/users",
    blocked: "/api/users/blocked",
    block: (id: string) => `/api/users/${id}/block`,
  },
  posts: {
    list: "/api/posts",
    byId: (id: string) => `/api/posts/${id}`,
    like: (id: string) => `/api/posts/${id}/like`,
    save: (id: string) => `/api/posts/${id}/save`,
    view: (id: string) => `/api/posts/${id}/view`,
    trending: "/api/posts/trending",
    recommended: "/api/posts/recommended",
    nearby: "/api/posts/nearby",
    search: "/api/posts/search",
    saved: "/api/posts/saved",
    byUser: (id: string) => `/api/posts/user/${id}`,
  },
  comments: {
    list: (postId: string) => `/api/comments/post/${postId}`,
    delete: (id: string) => `/api/comments/${id}`,
    like: (id: string) => `/api/comments/${id}/like`,
  },
  messages: {
    conversations: "/api/messages/conversations",
    messages: (id: string) => `/api/messages/conversations/${id}/messages`,
    send: (id: string) => `/api/messages/conversations/${id}/messages`,
    read: (id: string) => `/api/messages/conversations/${id}/read`,
  },
  groups: {
    list: "/api/groups",
    byId: (id: string) => `/api/groups/${id}`,
    messages: (id: string) => `/api/groups/${id}/messages`,
    participants: (id: string) => `/api/groups/${id}/participants`,
    join: (id: string) => `/api/groups/${id}/participants`,
    leave: (id: string, uid: string) => `/api/groups/${id}/participants/${uid}`,
  },
  notifications: {
    list: "/api/notifications",
    read: (id: string) => `/api/notifications/${id}/read`,
    readAll: "/api/notifications/read-all",
  },
  stories: {
    list: "/api/stories",
    byId: (id: string) => `/api/stories/${id}`,
    view: (id: string) => `/api/stories/${id}/view`,
    react: (id: string) => `/api/stories/${id}/react`,
    reply: (id: string) => `/api/stories/${id}/reply`,
  },
  library: {
    list: "/api/library",
    upload: "/api/library/upload",
    byId: (id: string) => `/api/library/${id}`,
    share: (id: string) => `/api/library/${id}/share`,
    unshare: (id: string) => `/api/library/${id}/unshare`,
  },
  collections: {
    list: "/api/collections",
    byId: (id: string) => `/api/collections/${id}`,
    items: (id: string) => `/api/collections/${id}/items`,
    addItem: (id: string) => `/api/collections/${id}/items`,
    removeItem: (id: string, aid: string) => `/api/collections/${id}/items/${aid}`,
  },
  admin: {
    dashboard: "/api/admin/dashboard",
    users: "/api/admin/users",
    logs: "/api/admin/logs",
    setUserRole: (id: string) => `/api/admin/users/${id}/role`,
    setVerified: (id: string) => `/api/admin/users/${id}/verified`,
  },
} as const;
