// Icon wrapper — react-iconly-like API
// Maps icon names to generated light/bold components
import React from "react";

import {
  HomeLight, HomeBold,
  SearchLight, SearchBold,
  DiscoveryLight, DiscoveryBold,
  ChatLight, ChatBold,
  UserLight, UserBold,
  PlusLight, PlusBold,
  ArrowLeftLight, ArrowLeftBold,
  ArrowRightLight, ArrowRightBold,
  ArrowLeft2Light, ArrowLeft2Bold,
  ArrowRight2Light, ArrowRight2Bold,
  ArrowDownLight, ArrowDownBold,
  ArrowUpLight, ArrowUpBold,
  CloseSquareLight, CloseSquareBold,
  SettingLight, SettingBold,
  LockLight, LockBold,
  LogoutLight, LogoutBold,
  SendLight, SendBold,
  CallLight, CallBold,
  CameraLight, CameraBold,
  VoiceLight, VoiceBold,
  Voice2Light, Voice2Bold,
  VideoLight, VideoBold,
  NotificationLight, NotificationBold,
  ImageLight, ImageBold,
  EditLight, EditBold,
  EditSquareLight, EditSquareBold,
  DeleteLight, DeleteBold,
  ShieldDoneLight, ShieldDoneBold,
  ShieldFailLight, ShieldFailBold,
  StarLight, StarBold,
  FilterLight, FilterBold,
  MoreCircleLight, MoreCircleBold,
  MoreSquareLight, MoreSquareBold,
  BookmarkLight, BookmarkBold,
  HeartLight, HeartBold,
  FolderLight, FolderBold,
  PlayLight, PlayBold,
  DocumentLight, DocumentBold,
  CalendarLight, CalendarBold,
  UploadLight, UploadBold,
  DownloadLight, DownloadBold,
  HideLight, HideBold,
  ShowLight, ShowBold,
  TimeCircleLight, TimeCircleBold,
  WalletLight, WalletBold,
  WorkLight, WorkBold,
  VolumeUpLight, VolumeUpBold,
  VolumeDownLight, VolumeDownBold,
  VolumeOffLight, VolumeOffBold,
  PaperPlusLight, PaperPlusBold,
  TicketLight, TicketBold,
  DiscountLight, DiscountBold,
  TickSquareLight, TickSquareBold,
  DangerLight, DangerBold,
  DangerCircleLight, DangerCircleBold,
  PaperLight, PaperBold,
  SwapLight, SwapBold,
  PaperUploadLight, PaperUploadBold,
  PaperDownloadLight, PaperDownloadBold,
  GraphLight, GraphBold,
  BuyLight, BuyBold,
  BankCardLight, BankCardBold,
  CategoryLight, CategoryBold,
  AddUserLight, AddUserBold,
  ActivityLight, ActivityBold,
  ScanLight, ScanBold,
  QrCodeLight, QrCodeBold,
  PaperFailLight, PaperFailBold,
  PaperNegativeLight, PaperNegativeBold,
  InfoSquareLight, InfoSquareBold,
  DangerTriangleLight, DangerTriangleBold,
  UnlockLight, UnlockBold,

  ArrowDown2Light, ArrowDown2Bold,
  ArrowDown3Light, ArrowDown3Bold,
  ArrowUp2Light, ArrowUp2Bold,
  ArrowUp3Light, ArrowUp3Bold,
  LocationLight, LocationBold,
  Location2Light, Location2Bold,
} from "./icons";

type IconSet = "light" | "bold";

interface IconProps {
  name: string;
  set?: IconSet;
  size?: number;
  color?: string;
  strokeWidth?: number;
  style?: any;
}

const iconMap: Record<string, { light: React.ComponentType<any>; bold: React.ComponentType<any> }> = {
  home: { light: HomeLight, bold: HomeBold },
  search: { light: SearchLight, bold: SearchBold },
  discovery: { light: DiscoveryLight, bold: DiscoveryBold },
  chat: { light: ChatLight, bold: ChatBold },
  user: { light: UserLight, bold: UserBold },
  plus: { light: PlusLight, bold: PlusBold },
  "arrow-left": { light: ArrowLeftLight, bold: ArrowLeftBold },
  "arrow-right": { light: ArrowRightLight, bold: ArrowRightBold },
  "arrow-left-2": { light: ArrowLeft2Light, bold: ArrowLeft2Bold },
  "arrow-right-2": { light: ArrowRight2Light, bold: ArrowRight2Bold },
  "arrow-down": { light: ArrowDownLight, bold: ArrowDownBold },
  "arrow-up": { light: ArrowUpLight, bold: ArrowUpBold },
  "close-square": { light: CloseSquareLight, bold: CloseSquareBold },
  setting: { light: SettingLight, bold: SettingBold },
  lock: { light: LockLight, bold: LockBold },
  logout: { light: LogoutLight, bold: LogoutBold },
  send: { light: SendLight, bold: SendBold },
  call: { light: CallLight, bold: CallBold },
  camera: { light: CameraLight, bold: CameraBold },
  voice: { light: VoiceLight, bold: VoiceBold },
  "voice-2": { light: Voice2Light, bold: Voice2Bold },
  video: { light: VideoLight, bold: VideoBold },
  notification: { light: NotificationLight, bold: NotificationBold },
  image: { light: ImageLight, bold: ImageBold },
  edit: { light: EditLight, bold: EditBold },
  "edit-square": { light: EditSquareLight, bold: EditSquareBold },
  delete: { light: DeleteLight, bold: DeleteBold },
  shield: { light: ShieldDoneLight, bold: ShieldDoneBold },
  "shield-fail": { light: ShieldFailLight, bold: ShieldFailBold },
  star: { light: StarLight, bold: StarBold },
  filter: { light: FilterLight, bold: FilterBold },
  "more-circle": { light: MoreCircleLight, bold: MoreCircleBold },
  "more-square": { light: MoreSquareLight, bold: MoreSquareBold },
  bookmark: { light: BookmarkLight, bold: BookmarkBold },
  heart: { light: HeartLight, bold: HeartBold },
  folder: { light: FolderLight, bold: FolderBold },
  play: { light: PlayLight, bold: PlayBold },
  document: { light: DocumentLight, bold: DocumentBold },
  calendar: { light: CalendarLight, bold: CalendarBold },
  upload: { light: UploadLight, bold: UploadBold },
  download: { light: DownloadLight, bold: DownloadBold },
  hide: { light: HideLight, bold: HideBold },
  show: { light: ShowLight, bold: ShowBold },
  "time-circle": { light: TimeCircleLight, bold: TimeCircleBold },
  wallet: { light: WalletLight, bold: WalletBold },
  work: { light: WorkLight, bold: WorkBold },
  "volume-up": { light: VolumeUpLight, bold: VolumeUpBold },
  "volume-down": { light: VolumeDownLight, bold: VolumeDownBold },
  "volume-off": { light: VolumeOffLight, bold: VolumeOffBold },
  "paper-plus": { light: PaperPlusLight, bold: PaperPlusBold },
  ticket: { light: TicketLight, bold: TicketBold },
  discount: { light: DiscountLight, bold: DiscountBold },
  "tick-square": { light: TickSquareLight, bold: TickSquareBold },
  danger: { light: DangerLight, bold: DangerBold },
  "danger-circle": { light: DangerCircleLight, bold: DangerCircleBold },
  paper: { light: PaperLight, bold: PaperBold },
  swap: { light: SwapLight, bold: SwapBold },
  "paper-upload": { light: PaperUploadLight, bold: PaperUploadBold },
  "paper-download": { light: PaperDownloadLight, bold: PaperDownloadBold },
  graph: { light: GraphLight, bold: GraphBold },
  buy: { light: BuyLight, bold: BuyBold },
  "bank-card": { light: BankCardLight, bold: BankCardBold },
  category: { light: CategoryLight, bold: CategoryBold },
  "add-user": { light: AddUserLight, bold: AddUserBold },
  activity: { light: ActivityLight, bold: ActivityBold },
  scan: { light: ScanLight, bold: ScanBold },
  qr: { light: QrCodeLight, bold: QrCodeBold },
  "paper-fail": { light: PaperFailLight, bold: PaperFailBold },
  "paper-negative": { light: PaperNegativeLight, bold: PaperNegativeBold },
  "info-square": { light: InfoSquareLight, bold: InfoSquareBold },
  "danger-triangle": { light: DangerTriangleLight, bold: DangerTriangleBold },
  unlock: { light: UnlockLight, bold: UnlockBold },

  "arrow-down-2": { light: ArrowDown2Light, bold: ArrowDown2Bold },
  "arrow-down-3": { light: ArrowDown3Light, bold: ArrowDown3Bold },
  "arrow-up-2": { light: ArrowUp2Light, bold: ArrowUp2Bold },
  "arrow-up-3": { light: ArrowUp3Light, bold: ArrowUp3Bold },
  location: { light: LocationLight, bold: LocationBold },
  "location-2": { light: Location2Light, bold: Location2Bold },
};

export function Icon({ name, set = "light", size = 24, color, strokeWidth, style }: IconProps) {
  const icon = iconMap[name];
  if (!icon) {
    console.warn(`Icon "${name}" not found`);
    return null;
  }
  const Comp = icon[set];
  return <Comp size={size} color={color} strokeWidth={strokeWidth} style={style} />;
}

export type { IconProps, IconSet };
